/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.johnathanperez.javaproject;

public class App {
    public String fizzbuzzword (int i) {
        if (i % 15 == 0) {
           return "fizzbuzz";
        
        } else if (i % 5 == 0) {
            return "buzz";
        
        } else if (i % 3 == 0) {
            return "fizz";
        
        } else {
            return String.valueOf(i);
        }

        
    }



    public static void main(String[] args){

        App fizzBuzzApp;
        fizzBuzzApp = new App();
    
        int i;    
        for (i=1; i<101; i++ ){
             System.out.println(fizzBuzzApp.fizzbuzzword(i));

        }
    }

    
}
