/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.johnathanperez.javaproject;

public class App {
    public String fizzbuzzword (int i)
    
    int i = 123;
    {
        if (i % 15 == 0) {
           return "fizzbuzz";
        
        } else if (i % 5 == 0) {
            return "buzz";
        
        } else if (i % 3 == 0) {
            return "fizz";
        
        } else {return String (i) i}

        
    }



    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
