/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.johnathanperez.javaproject;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void fizzbuzzwordReturnsValue() {
        App classUnderTest = new App();
        int i = 10;
        assertEquals("buzz", classUnderTest.fizzbuzzword(i));
         i = 30;
         assertEquals("fizzbuzz", classUnderTest.fizzbuzzword(i));
         i = 33;
         assertEquals("fizz", classUnderTest.fizzbuzzword(i));
         i = 99;
         assertEquals("fizz", classUnderTest.fizzbuzzword(i));
         i = 44;
         assertEquals("44", classUnderTest.fizzbuzzword(i));
         i = 1;
         assertEquals("1", classUnderTest.fizzbuzzword(i));
         i = 90;
         assertEquals("fizzbuzz", classUnderTest.fizzbuzzword(i));

    }
}